#!/usr/bin/env python3
"""gen_lp.py — 低精度浮点转换 handler 生成器"""

import yaml, os, sys
from textwrap import dedent

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "handles")


def gen_lp_convert(inst):
    name = inst["name"]
    direction = inst["dir"]       # "to_f32" or "from_f32"
    load_expr = inst["load"]      # expression to compute result
    store_fn = inst.get("store_fn", "")

    if direction == "to_f32":
        body = f"FPR(rd, _li) = {load_expr};"
    else:
        body = f"uint32_t val = {load_expr};\n"
        body += f"            {store_fn};"

    return dedent(f"""\
    op_{name}:
    {{
        int rd = ip[-1].rd, rs1 = ip[-1].rs1;
        FOR_EACH_LANE
        {{
            {body}
            PC(_li) += 4;
        }}
        NEXT();
    }}
    """)


GEN_FN = {"lp_convert": gen_lp_convert}


def generate(spec_path):
    with open(spec_path) as f:
        spec = yaml.safe_load(f)
    os.makedirs(OUT_DIR, exist_ok=True)
    for family in spec["families"]:
        name = family["name"]
        output = f"/* lp_{name}.h — {family.get('desc', name)}\n * Auto-generated by gen_lp.py — DO NOT EDIT\n */\n"
        gen_fn = GEN_FN[family["template"]]
        for inst in family["instructions"]:
            output += gen_fn(inst) + "\n"
        fname = os.path.join(OUT_DIR, f"lp_{name}.h")
        with open(fname, "w") as f:
            f.write(output)
        print(f"  GEN  lp_{name}.h")
    all_lines = ["/* lp_all.h — Auto-generated */", ""]
    for fam in spec["families"]:
        all_lines.append(f'#include "lp_{fam["name"]}.h"')
    all_lines.append("")
    with open(os.path.join(OUT_DIR, "lp_all.h"), "w") as f:
        f.write("\n".join(all_lines))
    print(f"  GEN  lp_all.h")


if __name__ == "__main__":
    sp = sys.argv[1] if len(sys.argv) > 1 else os.path.join(SCRIPT_DIR, "lp_spec.yaml")
    generate(sp)
