#!/usr/bin/env python3
"""gen_sf.py — SF 快速数学近似 handler 生成器"""

import yaml, os, sys
from textwrap import dedent

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "handles")


def gen_sf(inst):
    return dedent(f"""\
    op_{inst['name']}:
    {{
        int rd = ip[-1].rd, rs1 = ip[-1].rs1;
        FOR_EACH_LANE
        {{
            float v = FR(rs1, _li);
            FR(rd, _li) = {inst['expr']};
            PC(_li) += 4;
        }}
        NEXT();
    }}
    """)


def gen_vf_unary(inst):
    """向量 SFU 一元 (custom-1 0x2B, 无 SEW 变体)"""
    return dedent(f"""\
    op_{inst['name']}:
    {{
        int vd = ip[-1].rd, vs1 = ip[-1].rs1;
        FOR_EACH_LANE
        {{
            if ((uint32_t)_li < _vl) {{
                float v = *(float *)&VR(vs1, _li);
                *(float *)&VR(vd, _li) = (float)({inst['expr']});
            }}
            PC(_li) += 4;
        }}
        NEXT();
    }}
    """)


def gen_vf_reduce(inst):
    """向量 SFU 归约 (custom-1 0x2B, 无 SEW 变体)"""
    op = inst.get("op", "sum")
    if op == "max":
        body = "float v = *(float *)&VR(vs1, _li); if (isnan(mx) || v > mx) mx = v;"
        init = "float mx = NAN;"
        result = "FR(rd, 0) = mx;"
    else:
        body = "sum += *(float *)&VR(vs1, _li);"
        init = "float sum = 0;"
        result = "FR(rd, 0) = sum;"
    return dedent(f"""\
    op_{inst['name']}:
    {{
        int rd = ip[-1].rd, vs1 = ip[-1].rs1;
        {init}
        FOR_EACH_LANE
        {{
            {body}
            PC(_li) += 4;
        }}
        {result}
        NEXT();
    }}
    """)


GEN_FN = {"sf": gen_sf, "sf_vec": gen_vf_unary, "sf_red": gen_vf_reduce}


def generate(spec_path):
    with open(spec_path) as f:
        spec = yaml.safe_load(f)
    os.makedirs(OUT_DIR, exist_ok=True)
    for family in spec["families"]:
        name = family["name"]
        output = f"/* sf_{name}.h — {family.get('desc', name)}\n * Auto-generated by gen_sf.py — DO NOT EDIT\n */\n"
        gen_fn = GEN_FN[family["template"]]
        for inst in family["instructions"]:
            output += gen_fn(inst) + "\n"
        fname = os.path.join(OUT_DIR, f"sf_{name}.h")
        with open(fname, "w") as f:
            f.write(output)
        print(f"  GEN  sf_{name}.h")
    all_lines = ["/* sf_all.h — Auto-generated */", ""]
    for fam in spec["families"]:
        all_lines.append(f'#include "sf_{fam["name"]}.h"')
    all_lines.append("")
    with open(os.path.join(OUT_DIR, "sf_all.h"), "w") as f:
        f.write("\n".join(all_lines))
    print(f"  GEN  sf_all.h")


if __name__ == "__main__":
    sp = sys.argv[1] if len(sys.argv) > 1 else os.path.join(SCRIPT_DIR, "sf_spec.yaml")
    generate(sp)
