#!/usr/bin/env python3
"""gen_rv32m.py — RV32M multiply/divide handler 生成器"""

import yaml, os, sys
from textwrap import dedent

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "handles")

# mul: int32_t * int32_t → low 32 bits (already covered by RV32I alu_reg)
# mulh: (int64_t)(int32_t)a * (int64_t)(int32_t)b >> 32
# mulhsu: (int64_t)(int32_t)a * (uint64_t)b >> 32
# mulhu: (uint64_t)a * (uint64_t)b >> 32
# div:  int32_t / int32_t, INT32_MIN/-1 special
# divu: uint32_t / uint32_t, div-by-0 → -1
# rem:  int32_t % int32_t, INT32_MIN/-1 → 0
# remu: uint32_t % uint32_t, div-by-0 → dividend

TEMPLATES = {
    "mul":  "GPR(rd, _li) = GPR(rs1, _li) * GPR(rs2, _li);",
    "mulh": "GPR(rd, _li) = (uint32_t)(((int64_t)(int32_t)GPR(rs1, _li) * (int64_t)(int32_t)GPR(rs2, _li)) >> 32);",
    "mulhsu": "GPR(rd, _li) = (uint32_t)(((int64_t)(int32_t)GPR(rs1, _li) * (uint64_t)GPR(rs2, _li)) >> 32);",
    "mulhu": "GPR(rd, _li) = (uint32_t)(((uint64_t)GPR(rs1, _li) * (uint64_t)GPR(rs2, _li)) >> 32);",
    "div": """int32_t a = (int32_t)GPR(rs1, _li), b = (int32_t)GPR(rs2, _li);
        GPR(rd, _li) = b ? (uint32_t)((a == INT32_MIN && b == -1) ? INT32_MIN : a / b) : (uint32_t)-1;""",
    "divu": """uint32_t a = GPR(rs1, _li), b = GPR(rs2, _li);
        GPR(rd, _li) = b ? a / b : 0xFFFFFFFF;""",
    "rem": """int32_t a = (int32_t)GPR(rs1, _li), b = (int32_t)GPR(rs2, _li);
        GPR(rd, _li) = b ? (uint32_t)((a == INT32_MIN && b == -1) ? 0 : a % b) : GPR(rs1, _li);""",
    "remu": """uint32_t a = GPR(rs1, _li), b = GPR(rs2, _li);
        GPR(rd, _li) = b ? a % b : a;""",
}


def gen_mul_div(inst):
    body = TEMPLATES[inst["type"]]
    return dedent(f"""\
    op_{inst['name']}:
    {{
        int rd = ip[-1].rd, rs1 = ip[-1].rs1, rs2 = ip[-1].rs2;
        FOR_EACH_LANE
        {{
            {body}
            PC(_li) += 4;
        }}
        NEXT();
    }}
    """)


GEN_FN = {"mul_div": gen_mul_div}


def generate(spec_path):
    with open(spec_path) as f:
        spec = yaml.safe_load(f)
    os.makedirs(OUT_DIR, exist_ok=True)
    for family in spec["families"]:
        name = family["name"]
        output = f"/* rv32m_{name}.h — {family.get('desc', name)}\n * Auto-generated by gen_rv32m.py — DO NOT EDIT\n */\n"
        gen_fn = GEN_FN[family["template"]]
        for inst in family["instructions"]:
            output += gen_fn(inst) + "\n"
        fname = os.path.join(OUT_DIR, f"rv32m_{name}.h")
        with open(fname, "w") as f:
            f.write(output)
        print(f"  GEN  rv32m_{name}.h")
    # all include
    all_lines = ["/* rv32m_all.h — Auto-generated */", ""]
    for fam in spec["families"]:
        all_lines.append(f'#include "rv32m_{fam["name"]}.h"')
    all_lines.append("")
    with open(os.path.join(OUT_DIR, "rv32m_all.h"), "w") as f:
        f.write("\n".join(all_lines))
    print(f"  GEN  rv32m_all.h")


if __name__ == "__main__":
    sp = sys.argv[1] if len(sys.argv) > 1 else os.path.join(SCRIPT_DIR, "rv32m_spec.yaml")
    generate(sp)
