#!/usr/bin/env python3
"""gen_rv32zicsr.py — Zicsr CSR 指令 handler 生成器"""

import yaml, os, sys
from textwrap import dedent

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "handles")

# CSR body templates by mode
# rw: rd=old, csr=rs1 (read+write)
# rs: rd=old, csr|=rs1 (read+set bits)
# rc: rd=old, csr&=~rs1 (read+clear bits)

CSR_BODY_RW = """\
switch (csr) {{
        case CSR_MHARTID: old = MHARTID(_li); break;
        case CSR_FFLAGS: old = FCSR(_li) & 0x1F; FCSR(_li) = (FCSR(_li) & ~0x1F) | (GPR(rs1, _li) & 0x1F); break;
        case CSR_FRM: old = (FCSR(_li) >> 5) & 7; FCSR(_li) = (FCSR(_li) & ~0xE0) | ((GPR(rs1, _li) & 7) << 5); break;
        case CSR_FCSR: old = FCSR(_li); FCSR(_li) = GPR(rs1, _li); break;
    }}"""

CSR_BODY_RS = """\
switch (csr) {{
        case CSR_MHARTID: old = MHARTID(_li); break;
        case CSR_FFLAGS: old = FCSR(_li) & 0x1F; if (rs1) FCSR(_li) |= (mask & 0x1F); break;
        case CSR_FRM: old = (FCSR(_li) >> 5) & 7; if (rs1) FCSR(_li) |= ((mask & 7) << 5); break;
        case CSR_FCSR: old = FCSR(_li); if (rs1) FCSR(_li) |= mask; break;
    }}"""

CSR_BODY_RC = """\
switch (csr) {{
        case CSR_MHARTID: old = MHARTID(_li); break;
        case CSR_FFLAGS: old = FCSR(_li) & 0x1F; if (rs1) FCSR(_li) &= ~(mask & 0x1F); break;
        case CSR_FRM: old = (FCSR(_li) >> 5) & 7; if (rs1) FCSR(_li) &= ~((mask & 7) << 5); break;
        case CSR_FCSR: old = FCSR(_li); if (rs1) FCSR(_li) &= ~mask; break;
    }}"""


def gen_csr(inst):
    name = inst["name"]
    mode = inst["mode"]
    use_imm = inst["use_imm"]

    if use_imm:
        zimm = "ip[-1].imm"
        zexpr = "(uint32_t)ip[-1].imm"
        rs1_check = "(ip[-1].rs1)"  # rs1 field used as uimm[4:0]
    else:
        zimm = "GPR(rs1, _li)"
        zexpr = "GPR(rs1, _li)"
        rs1_check = "rs1"

    if mode == "rw":
        body = dedent(f"""\
            uint32_t old = 0;
            {CSR_BODY_RW.replace('GPR(rs1, _li)', zexpr)}
            GPR(rd, _li) = old;""")
        vars_decl = f"int rd = ip[-1].rd, rs1 = ip[-1].rs1;"
    elif mode == "rs":
        body = dedent(f"""\
            uint32_t old = 0, mask = {zexpr};
            {CSR_BODY_RS}
            GPR(rd, _li) = old;""")
        vars_decl = f"int rd = ip[-1].rd, rs1 = ip[-1].rs1;"
    elif mode == "rc":
        body = dedent(f"""\
            uint32_t old = 0, mask = {zexpr};
            {CSR_BODY_RC}
            GPR(rd, _li) = old;""")
        vars_decl = f"int rd = ip[-1].rd, rs1 = ip[-1].rs1;"

    return dedent(f"""\
    op_{name}:
    {{
        uint16_t csr = (uint16_t)ip[-1].imm;
        {vars_decl}
        FOR_EACH_LANE
        {{
            {body}
            PC(_li) += 4;
        }}
        NEXT();
    }}
    """)


GEN_FN = {"csr": gen_csr}


def generate(spec_path):
    with open(spec_path) as f:
        spec = yaml.safe_load(f)
    os.makedirs(OUT_DIR, exist_ok=True)
    for family in spec["families"]:
        name = family["name"]
        output = f"/* zicsr_{name}.h — {family.get('desc', name)}\n * Auto-generated by gen_rv32zicsr.py — DO NOT EDIT\n */\n"
        gen_fn = GEN_FN[family["template"]]
        for inst in family["instructions"]:
            output += gen_fn(inst) + "\n"
        fname = os.path.join(OUT_DIR, f"zicsr_{name}.h")
        with open(fname, "w") as f:
            f.write(output)
        print(f"  GEN  zicsr_{name}.h")
    all_lines = ["/* zicsr_all.h — Auto-generated */", ""]
    for fam in spec["families"]:
        all_lines.append(f'#include "zicsr_{fam["name"]}.h"')
    all_lines.append("")
    with open(os.path.join(OUT_DIR, "zicsr_all.h"), "w") as f:
        f.write("\n".join(all_lines))
    print(f"  GEN  zicsr_all.h")


if __name__ == "__main__":
    sp = sys.argv[1] if len(sys.argv) > 1 else os.path.join(SCRIPT_DIR, "rv32zicsr_spec.yaml")
    generate(sp)
