#!/usr/bin/env python3
"""gen_rv32a.py — RV32A 原子操作 handler 生成器"""

import yaml, os, sys
from textwrap import dedent

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "handles")


def gen_lr_sc(inst):
    if inst["type"] == "lr":
        return dedent("""\
        op_lr_w:
        {
            int rd = ip[-1].rd, rs1 = ip[-1].rs1;
            FOR_EACH_LANE
            {
                uint32_t a = GPR(rs1, _li);
                GPR(rd, _li) = ctrl_read(ctx, a, _li);
                PC(_li) += 4;
            }
            NEXT();
        }
        """)
    else:
        return dedent("""\
        op_sc_w:
        {
            int rd = ip[-1].rd, rs1 = ip[-1].rs1, rs2 = ip[-1].rs2;
            FOR_EACH_LANE
            {
                uint32_t a = GPR(rs1, _li);
                gpu_write(s, a, 4, GPR(rs2, _li));
                GPR(rd, _li) = 0;
                PC(_li) += 4;
            }
            NEXT();
        }
        """)


def gen_amo(inst):
    return dedent(f"""\
    op_{inst['name']}:
    {{
        int rd = ip[-1].rd, rs1 = ip[-1].rs1, rs2 = ip[-1].rs2;
        FOR_EACH_LANE
        {{
            uint32_t a = GPR(rs1, _li), v = GPR(rs2, _li);
            uint32_t old = ctrl_read(ctx, a, _li);
            gpu_write(s, a, 4, (uint32_t)({inst['expr']}));
            GPR(rd, _li) = old;
            PC(_li) += 4;
        }}
        NEXT();
    }}
    """)


GEN_FN = {"lr_sc": gen_lr_sc, "amo": gen_amo}


def generate(spec_path):
    with open(spec_path) as f:
        spec = yaml.safe_load(f)
    os.makedirs(OUT_DIR, exist_ok=True)
    for family in spec["families"]:
        name = family["name"]
        output = f"/* rv32a_{name}.h — {family.get('desc', name)}\n * Auto-generated by gen_rv32a.py — DO NOT EDIT\n */\n"
        gen_fn = GEN_FN[family["template"]]
        for inst in family["instructions"]:
            output += gen_fn(inst) + "\n"
        fname = os.path.join(OUT_DIR, f"rv32a_{name}.h")
        with open(fname, "w") as f:
            f.write(output)
        print(f"  GEN  rv32a_{name}.h")
    all_lines = ["/* rv32a_all.h — Auto-generated */", ""]
    for fam in spec["families"]:
        all_lines.append(f'#include "rv32a_{fam["name"]}.h"')
    all_lines.append("")
    with open(os.path.join(OUT_DIR, "rv32a_all.h"), "w") as f:
        f.write("\n".join(all_lines))
    print(f"  GEN  rv32a_all.h")


if __name__ == "__main__":
    sp = sys.argv[1] if len(sys.argv) > 1 else os.path.join(SCRIPT_DIR, "rv32a_spec.yaml")
    generate(sp)
